site_name: pygeoapi-prefect
repo_url: https://github.com/geobeyond/pygeoapi-prefect
repo_name: pygeoapi-prefect
site_description: pygeoapi process manager pwered by prefect
site_author: geobeyond
edit_uri: edit/main/docs/

nav:
  - Home: 'index.md'
  - User Guide:
      - Installation: 'user-guide/installation.md'
      - Defining processes: 'user-guide/defining-processes.md'
      - Running prefect: 'user-guide/prefect.md'
      - Deployments: 'user-guide/deployments.md'
      - Executing processes: 'user-guide/executing-processes.md'
      - Complete example: 'user-guide/complete-example.md'
  - Development: 'development.md'

theme:
  name: material
  palette:
    primary: blue grey
    accent: pink
  features:
    - content.action.edit
    - header.autohide
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
