name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.3.1

      - name: setup Python cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install package
        run: poetry install --with dev --with docs

      - name: run pre-commit
        run: poetry run pre-commit run --all-files

      - name: (Re)build docs
        run: poetry run mkdocs build

#      - name: Run tests
#        run: poetry run pytest --suppress-no-test-exit-code

  publish-docs:
    needs: ci
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry==1.3.1

      - name: setup Python cache
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: poetry

      - name: Install package
        run: poetry install --with dev --with docs

      - name: update docs
        run: poetry run mkdocs gh-deploy --force
